export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const SET_CART_ITEM_COUNT = "SET_CART_ITEM_COUNT";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const SET_FLAVOR_SELECTED = "SET_FLAVOR_SELECTED";
export const SET_QUANTITY_TO_CART = "SET_QUANTITY_TO_CART";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
